### ISSUE TITLE
generated plugin not starting . 

### ISSUE THREAD

**Issue by mpasindu** [elastic/kibana-plugin-helpers#63]
pasindu@pasindu:~/data/software/kibana/my-new-plugin$ npm start -- --elasticsearch.url 'http://localhost:9200'

> my_new_plugin@0.0.0 start /home/pasindu/data/software/kibana-6.1.3-linux-x86_64/my-new-plugin
> plugin-helpers start "--elasticsearch.url" "http://localhost:9200"

child_process.js:496
    throw err;
    ^

Error: spawnSync bin/kibana ENOENT
    at exports._errnoException (util.js:1020:11)
    at spawnSync (child_process.js:451:20)
    at execFileSync (child_process.js:488:13)
    at module.exports (/home/pasindu/data/software/kibana-6.1.3-linux-x86_64/my-new-plugin/node_modules/@elastic/plugin-helpers/tasks/start/start_action.js:13:3)
    at run (/home/pasindu/data/software/kibana-6.1.3-linux-x86_64/my-new-plugin/node_modules/@elastic/plugin-helpers/lib/run.js:9:10)
    at /home/pasindu/data/software/kibana-6.1.3-linux-x86_64/my-new-plugin/node_modules/@elastic/plugin-helpers/bin/plugin-helpers.js:27:7
    at Command.actionWrapper (/home/pasindu/data/software/kibana-6.1.3-linux-x86_64/my-new-plugin/node_modules/@elastic/plugin-helpers/bin/plugin-helpers.js:14:8)
    at Command.listener (/home/pasindu/data/software/kibana-6.1.3-linux-x86_64/my-new-plugin/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my_new_plugin@0.0.0 start: `plugin-helpers start "--elasticsearch.url" "http://localhost:9200"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my_new_plugin@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pasindu/.npm/_logs/2018-02-02T03_58_05_185Z-debug.log

**Comment by spalger** [comment]
Looks like it's trying to start Kibana but not finding it.

**Comment by w33ble** [comment]
Looks like you are running Kibana 6.1.3, are you also running 7.x of the helpers? See the compat chart [here](https://github.com/elastic/kibana-plugin-helpers#versions).

**Comment by mpasindu** [comment]
Yes you correct . I have change kibana version to master (7.x) . now it's working . 

Thank you .
