### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Shahid7001** [elastic/kibana-plugin-helpers#72]
Error: Cannot find module '../helper.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Gekko\gekko-develop\strategies\buyatsellat.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
RECEIVED ERROR IN GEKKO 0927221594944796
Child process has died.

**Comment by spalger** [comment]
This error is coming from `E:\Gekko\gekko-develop\strategies\buyatsellat.js:3:14`, which doesn't seem to have anything to do with Kibana or the plugin helpers.
